import { useEffect, useRef, useState } from "react";
import { useInView, useReducedMotion } from "motion/react";

import { PigLogo } from "@/components/PigLogo";
import activity from "./commit-activity.json";
import { Stagger, StaggerItem } from "./motion";

/**
 * Mini previews of each resource's destination, shown in the Resources card
 * image areas. The whitepaper page and activity grid are decorative (the card
 * title names the link); the X screenshot carries alt text. Hover effects key
 * off the card link's `group` class, are transform-only, and switch off under
 * reduced motion.
 */

const lift =
  "transition-transform duration-500 ease-out motion-reduce:transition-none motion-reduce:transform-none";

/** Whitepaper: a tilted document page that lifts and straightens on hover. */
export function WhitepaperPreview() {
  const lines = ["w-full", "w-11/12", "w-full", "w-4/5", "w-full", "w-3/5"];
  return (
    <div
      aria-hidden="true"
      className={`aspect-[3/4] w-[42%] -rotate-4 rounded-lg bg-white p-4 shadow-xl shadow-ink/10 group-hover:-translate-y-2 group-hover:rotate-0 sm:p-5 ${lift}`}
    >
      <PigLogo className="mb-3 h-6 w-6" />
      <p className="mb-3 text-[13px] font-semibold leading-tight text-ink sm:text-sm">OinkAI Whitepaper</p>
      <div className="space-y-1.5">
        {lines.map((w, i) => (
          <span key={i} className={`block h-1.5 rounded-full bg-ink/10 ${w}`} />
        ))}
      </div>
    </div>
  );
}

/** X: the real @oink_AI profile, as a floating screenshot. */
export function XProfilePreview() {
  return (
    <img
      src="/x-profile.webp"
      alt="OinkAI's profile on X"
      width={1215}
      height={918}
      loading="lazy"
      decoding="async"
      className={`h-auto w-[78%] rotate-3 rounded-2xl shadow-2xl shadow-brand-light/15 group-hover:-translate-y-2 group-hover:rotate-0 ${lift}`}
    />
  );
}

// Real commits per day from this repo, generated by scripts/commit-activity.mjs.
const weeks = activity.weeks as (number | null)[][];
// Column-major (week by week) so the fill-in stagger sweeps left to right.
const days = weeks.flat();
const filled = days.flatMap((n, i) => (n ? [i] : []));

function levelClass(n: number | null) {
  if (n === null) return "invisible"; // after the latest commit
  if (n === 0) return "bg-ink/[0.07]";
  if (n === 1) return "bg-brand-dark/40";
  if (n <= 3) return "bg-brand-dark/70";
  if (n <= 8) return "bg-brand-dark/90";
  return "bg-brand-dark";
}

/**
 * A few filled squares softly brighten and fade back every ~1.6s, like live
 * activity. Client-only (random), paused off-screen and under reduced motion.
 */
function useTwinkle(active: boolean) {
  const [lit, setLit] = useState<number[]>([]);
  useEffect(() => {
    if (!active || filled.length === 0) return;
    let clear: ReturnType<typeof setTimeout> | undefined;
    const tick = () => {
      const picks = new Set<number>();
      while (picks.size < Math.min(2, filled.length)) {
        picks.add(filled[Math.floor(Math.random() * filled.length)]);
      }
      setLit([...picks]);
      clear = setTimeout(() => setLit([]), 900);
    };
    const id = setInterval(tick, 1600);
    return () => {
      clearInterval(id);
      clearTimeout(clear);
      setLit([]);
    };
  }, [active]);
  return lit;
}

/**
 * GitHub: this repo's real commit activity (columns = weeks, rows = Sun–Sat,
 * most recent on the right), filling in with a quick stagger, over a real
 * call from contracts/OinkSafe.sol.
 */
export function GitHubPreview() {
  const ref = useRef<HTMLDivElement>(null);
  const inView = useInView(ref);
  const reduce = useReducedMotion();
  const lit = useTwinkle(inView && !reduce);

  return (
    <div ref={ref} aria-hidden="true" className="flex w-[80%] flex-col items-center gap-4 sm:gap-5">
      <Stagger
        stagger={0.004}
        className="grid w-full grid-flow-col grid-rows-7 gap-[3px] sm:gap-1"
        style={{ gridTemplateColumns: `repeat(${weeks.length}, minmax(0, 1fr))` }}
      >
        {days.map((n, i) => (
          <StaggerItem key={i} y={0} className={`relative aspect-square rounded-[3px] ${levelClass(n)}`}>
            {n ? (
              <span
                className={`absolute inset-0 rounded-[3px] bg-white transition-[opacity,transform] duration-700 ease-in-out ${
                  lit.includes(i) ? "scale-110 opacity-60" : "scale-100 opacity-0"
                }`}
              />
            ) : null}
          </StaggerItem>
        ))}
      </Stagger>
      <code className="max-w-full truncate rounded-full bg-ink px-4 py-2 font-mono text-xs text-brand-light sm:text-[13px]">
        OinkSafe.lock(amount, durationDays)
      </code>
    </div>
  );
}
